services:
  db:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=pw"
      - "POSTGRES_DB=postdb"
      - "TZ=Asia/Seoul"
    networks:
      - dbcon

  app:
    build:
      context: ./Backend/application-api
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:pw@host.docker.internal:5432/postdb?schema=public
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dbcon
    command: ["bash", "-c", "npx prisma db push && yarn start"]

  worker:
    build:
      context: ./Backend/worker-api
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    restart: always
    networks:
      - dbcon
    command: ["bash", "-c", "yarn start"]

  tts:
    build:
      context: ./Backend/inference-api
      dockerfile: ./Dockerfile
    ports:
      - "4500:4500"
    restart: always
    networks:
      - dbcon
    command: ["python", "main.py"]

  front:
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    restart: always
    networks:
      - dbcon
    command: ["bash", "-c", "yarn start"]

networks:
  dbcon:
    driver: bridge
